# Generated by Django 5.2.3 on 2025-06-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='code_of_conduct',
        ),
        migrations.AddField(
            model_name='unitcodeofconduct',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='codes_of_conduct', to='pages.unit'),
            preserve_default=False,
        ),
    ]
