# Generated by Django 5.2.3 on 2025-06-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_unit_code_of_conduct_unitcodeofconduct_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='members',
        ),
    ]
