# Generated by Django 5.2.3 on 2025-06-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_unit_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagebanner',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Home Page Banners'},
        ),
        migrations.AlterModelOptions(
            name='homepagehero',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Home Page Heroes'},
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='action',
            field=models.CharField(choices=[('learn_more', 'Learn More'), ('sign_up', 'Sign Up'), ('fill_form', 'Fill Form'), ('contact_us', 'Contact Us')], default='learn_more', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='action_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='event',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='for_workers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/mobile_images'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
