# Generated by Django 5.2.3 on 2025-06-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homepagebanner_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebanner',
            name='visibility',
            field=models.CharField(choices=[('published', 'Published (Visible to everyone)'), ('workers', 'Workers Only'), ('draft', 'Draft (Not visible to anyone)')], default='published', help_text='Who can see this banner?', max_length=20),
        ),
    ]
