# Generated by Django 5.2.3 on 2025-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_homepagebanner_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagehero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='event',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/mobile_images'),
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
