# Generated by Django 5.2.3 on 2025-06-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_homepagehero_created_at_homepagehero_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagehero',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
