# Generated by Django 5.2.3 on 2025-06-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_homepagehero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('for_workers', models.BooleanField(default=False)),
                ('for_website', models.BooleanField(default=True)),
                ('for_email', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('published', 'Published (Visible to everyone)'), ('workers', 'Workers Only'), ('draft', 'Draft (Not visible to anyone)')], default='published', help_text='Who can see this announcement?', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('event', 'Event'), ('news', 'News'), ('alert', 'Alert'), ('reminder', 'Reminder')], default='general', help_text='Category of the announcement', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
