# Generated by Django 5.2.3 on 2025-06-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='for_workers',
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images/'),
        ),
    ]
