# Generated by Django 5.2.3 on 2025-06-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_announcement_for_workers_announcement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=250, null=True)),
                ('event_date', models.DateField(blank=True, help_text='Date of the event related to this drive link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('published', 'Published (Visible to everyone)'), ('workers', 'Workers Only'), ('draft', 'Draft (Not visible to anyone)')], default='published', help_text='Who can see this drive link?', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Drive Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
