# Generated by Django 5.2.3 on 2025-06-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_drivelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivelink',
            name='for_workers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivelink',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
