# Generated by Django 5.2.3 on 2025-07-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_event_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this a default event that recurs every semester?'),
        ),
    ]
