# Generated by Django 5.2.3 on 2025-07-03 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_event_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='unit-announcements/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('for_website', models.BooleanField(default=True)),
                ('for_email', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('published', 'Published (Visible to everyone, Pending approval from the General Secretary)'), ('unit_members', 'Unit Members (Visible to only your unit members)'), ('draft', 'Draft (Not visible to anyone)')], default='published', help_text='Who can see this announcement?', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('event', 'Event'), ('news', 'News'), ('alert', 'Alert'), ('reminder', 'Reminder')], default='general', help_text='Category of the announcement', max_length=20)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_announcements', to='pages.unit')),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
