# Generated by Django 5.2.3 on 2025-07-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_unitannouncement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitannouncement',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Unit Announcements'},
        ),
    ]
