# Generated by Django 5.2.3 on 2025-07-04 08:07

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_unitannouncement_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for the article', null=True, upload_to='academic-articles/thumbnails/')),
                ('content', markdownx.models.MarkdownxField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateField(blank=True, help_text='Date of publication', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('for_workers', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('published', 'Published (Visible to everyone)'), ('workers', 'Workers Only'), ('draft', 'Draft (Not visible to anyone)')], default='published', help_text='Who can see this article?', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Academic Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
