# Generated by Django 5.2.3 on 2025-07-04 08:18

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_academicarticle'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicarticle',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="Tags for the article, e.g., 'Book, God, Faith'", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
