# Generated by Django 5.2.3 on 2025-07-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_academicarticle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
