# Generated by Django 5.2.3 on 2025-07-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_academicarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicarticle',
            name='content',
            field=models.TextField(help_text='Content of the article in Markdown format'),
        ),
    ]
