# Generated by Django 5.2.3 on 2025-07-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_academicarticle_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='course/materials')),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Educational Material',
                'verbose_name_plural': 'Educational Materials',
                'ordering': ['-uploaded_at', 'title'],
            },
        ),
    ]
