# Generated by Django 5.2.3 on 2025-07-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_academicarticle_publication_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivationalwriteup',
            old_name='header',
            new_name='title',
        ),
    ]
