# Generated by Django 5.2.3 on 2025-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_rename_header_motivationalwriteup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivationalwriteup',
            name='upload_date',
            field=models.DateTimeField(blank=True, help_text='Date of upload', null=True),
        ),
    ]
