# Generated by Django 5.2.3 on 2025-07-07 16:50

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_motivationalwriteup_upload_date'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(help_text='Link to the scholarship application', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the scholarship', max_digits=10)),
                ('eligibility_criteria', models.TextField(help_text='Eligibility criteria for the scholarship')),
                ('deadline', models.DateTimeField(blank=True, help_text='Application deadline', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image related to the scholarship', null=True, upload_to='scholarships/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('for_workers', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('published', 'Published (Visible to everyone)'), ('workers', 'Workers Only'), ('draft', 'Draft (Not visible to anyone)')], default='published', help_text='Who can see this scholarship?', max_length=20)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text="Tags for the scholarship, e.g., 'Undergraduate, Scholarship, Funding'", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
