# Generated by Django 5.2.3 on 2025-07-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the countdown', max_length=200)),
                ('description', models.TextField(help_text='Description of the countdown')),
                ('target_date', models.DateTimeField(help_text='Target date for the countdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countdowns',
                'ordering': ['-created_at'],
            },
        ),
    ]
