# Generated by Django 5.2.3 on 2025-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='target_date',
            field=models.DateField(help_text='Target date for the countdown'),
        ),
    ]
