# Generated by Django 5.2.3 on 2025-07-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('preached_date', models.DateField()),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
