# Generated by Django 5.2.3 on 2025-07-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('published', 'Published (Visible to everyone)'), ('draft', 'Draft (Not visible to anyone)')], default='published', help_text='Who can see this announcement?', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('event', 'Event'), ('news', 'News'), ('alert', 'Alert'), ('reminder', 'Reminder')], default='general', help_text='Category of the announcement', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('SERMON_UPLOAD', 'Added New Sermon'), ('EVENT_UPLOAD', 'Added New Event'), ('BANNER_UPDATE', 'Updated the Homepage Banner'), ('HERO_UPDATE', 'Updated the Homepage Hero Section'), ('DRIVE_UPLOAD', 'Uploaded New Photo Drive Link'), ('SEMESTER_CREATE', 'Created New Semester'), ('CALENDAR_CREATE', 'Created New Calendar'), ('ANNOUNCEMENT_PUBLISH', 'Published New Announcement'), ('UNIT_LEAVE', 'Unit Leave')], default='SERMON_UPLOAD', max_length=20)),
            ],
            options={
                'verbose_name': 'Recent Activity',
                'verbose_name_plural': 'Recent Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['date_preached']},
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='preached_date',
        ),
        migrations.AddField(
            model_name='sermon',
            name='bible_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='bible_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='date_preached',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='preacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='sermon_series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='sermon_type',
            field=models.CharField(choices=[('SS', 'Sunday Service'), ('BS', 'Bible Study Service'), ('SE', 'Special Event')], default='SS', max_length=2),
        ),
        migrations.AddField(
            model_name='sermon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
