# Generated by Django 5.2.3 on 2025-07-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homepagehero'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=250, null=True)),
                ('event_date', models.DateField(blank=True, help_text='Date of the event related to this drive link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Drive Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
