# Generated by Django 5.2.3 on 2025-06-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_date_joined'),
        ('pages', '0003_remove_unit_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='units',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_units', to='pages.unit'),
        ),
    ]
