# Generated by Django 5.2.3 on 2025-06-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_file', models.FileField(upload_to='sermons/%Y/%m/%d/')),
                ('preacher', models.CharField(blank=True, max_length=100, null=True)),
                ('date_preached', models.DateField(blank=True, null=True)),
                ('sermon_type', models.CharField(choices=[('SS', 'Sunday Service'), ('BS', 'Bible Study Service'), ('SE', 'Special Event')], default='SS', max_length=2)),
                ('bible_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('bible_text', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sermon_series', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
