# Generated by Django 5.2.3 on 2025-06-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_uploadsermon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadSermon',
            new_name='Sermon',
        ),
    ]
