# Generated by Django 5.2.3 on 2025-06-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_uploadsermon_sermon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-date_preached']},
        ),
    ]
