# Generated by Django 5.2.3 on 2025-07-02 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_sermon_options'),
        ('pages', '0016_event_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('SERMON_UPLOAD', 'Added New Sermon'), ('EVENT_UPLOAD', 'Added New Event'), ('BANNER_UPDATE', 'Updated the Homepage Banner'), ('HERO_UPDATE', 'Updated the Homepage Hero Section'), ('DRIVE_UPLOAD', 'Uploaded New Photo Drive Link'), ('SEMESTER_CREATE', 'Created New Semester'), ('CALENDAR_CREATE', 'Created New Calendar'), ('ANNOUNCEMENT_PUBLISH', 'Published New Announcement'), ('UNIT_LEAVE', 'Unit Leave')], default='SERMON_UPLOAD', max_length=20)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to='pages.unit')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
