# Generated by Django 5.2.3 on 2025-07-03 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_recentactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentactivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Recent Activity', 'verbose_name_plural': 'Recent Activities'},
        ),
    ]
