# Generated by Django 5.2.3 on 2025-07-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_email'),
        ('pages', '0031_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='units',
        ),
        migrations.AddField(
            model_name='profile',
            name='other_units',
            field=models.ManyToManyField(blank=True, related_name='other_members', to='pages.unit'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='pages.unit'),
        ),
    ]
