# Generated by Django 5.2.3 on 2025-07-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_units_profile_other_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentactivity',
            name='unit',
        ),
    ]
