# Generated by Django 5.2.3 on 2025-07-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_recentactivity_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentActivity',
        ),
        migrations.DeleteModel(
            name='Sermon',
        ),
    ]
